import { describe, it, expect, vi, beforeEach } from 'vitest'
import { mount, flushPromises } from '@vue/test-utils'
import { createI18n } from 'vue-i18n'
import ObservedStatusCards from '../ObservedStatusCards.vue'
import { observedCardValue } from '../observedCardFormat'
import { getCards } from '@/api/channelMonitorV2'

vi.mock('@/api/channelMonitorV2', () => ({ getCards: vi.fn() }))
const filter = { range: '24h' as const, platforms: [], groupIds: [], models: [] }
const response = () => ({ items: [{ identity: { platform: 'openai', group_id: 1, model: 'fixture' }, display: { group_label: 'Public group', platform_label: 'OpenAI', model_label: 'Fixture' }, windows: { h24: { output_tps_p50_milli: 41578, observed_ttft_p90_ms: 1000 }, d7: { output_tps_reason: 'partial_coverage' } } }], has_more: true, as_of: '2026-09-09T00:00:00Z', stale: false })
const create = () => mount(ObservedStatusCards, { props: { filter }, global: { plugins: [createI18n({ legacy: false, locale: 'en', messages: { en: {} } })] } })

describe('observed card formatting', () => {
  it('converts milli TPS without using aggregate throughput', () => {
    expect(observedCardValue({ output_tps_p50_milli: 41578 }, 'tps')).toBe('~ 41.58 tok/s')
    expect(observedCardValue({ output_tps_p50_milli: 0 }, 'tps')).toBe('~ 0.00 tok/s')
    for (const value of [undefined, null, NaN, Infinity, -1, 0.5]) expect(observedCardValue({ output_tps_p50_milli: value }, 'tps')).toBe('-')
    for (const reason of ['no_data', 'partial_coverage', 'out_of_range'] as const) expect(observedCardValue({ output_tps_p50_milli: 1000, output_tps_reason: reason }, 'tps')).toBe('-')
    expect(observedCardValue({}, 'ttft')).toBe('-')
    expect(observedCardValue({ observed_cache_read_ratio: .1 }, 'cache')).toBe('10.0%')
    expect(observedCardValue({ observed_cache_read_ratio: 0 }, 'cache')).toBe('0.0%')
    expect(observedCardValue({ cache_read_ratio: .9 }, 'cache')).toBe('-')
    for (const ratio of [null, undefined, NaN, Infinity, -1, 1.1]) expect(observedCardValue({ observed_cache_read_ratio: ratio }, 'cache')).toBe('-')
    expect(observedCardValue({ observed_cache_read_ratio: .1, observed_cache_reason: 'partial_coverage' }, 'cache')).toBe('-')
  })
})
describe('ObservedStatusCards', () => {
  beforeEach(() => { vi.resetAllMocks(); vi.mocked(getCards).mockResolvedValue(response() as never) })
  it('shows independent measurements, switches windows and pins pagination', async () => {
    const wrapper = create()
    await flushPromises()
    expect(wrapper.text()).toContain('~ 41.58 tok/s')
    expect(wrapper.text()).toContain('~ 1000 ms')
    await wrapper.findAll('[role="tab"]')[1]!.trigger('click')
    expect(wrapper.text()).toContain('Incomplete collection coverage')
    expect(wrapper.text()).not.toContain('41.58')
    await wrapper.find('[aria-label="Next page"]').trigger('click')
    await flushPromises()
    expect(getCards).toHaveBeenLastCalledWith(filter, { page: 2, page_size: 12, as_of: '2026-09-09T00:00:00Z' }, false, expect.any(AbortSignal))
    await wrapper.find('[aria-label="Previous page"]').trigger('click')
    await flushPromises()
    expect(getCards).toHaveBeenLastCalledWith(filter, { page: 1, page_size: 12, as_of: '2026-09-09T00:00:00Z' }, false, expect.any(AbortSignal))
    await wrapper.find('[aria-label="Refresh"]').trigger('click')
    await flushPromises()
    expect(getCards).toHaveBeenLastCalledWith(filter, { page: 1, page_size: 12, as_of: undefined }, false, expect.any(AbortSignal))
    wrapper.unmount()
  })
  it('resets pagination on page refresh and switches endpoint when role changes', async () => {
    const wrapper = create()
    await flushPromises()
    await wrapper.find('[aria-label="Next page"]').trigger('click')
    await flushPromises()
    await wrapper.setProps({ refreshKey: 1 })
    await flushPromises()
    expect(getCards).toHaveBeenLastCalledWith(filter, { page: 1, page_size: 12, as_of: undefined }, false, expect.any(AbortSignal))
    expect(wrapper.find('[aria-label="Previous page"]').attributes('disabled')).toBeDefined()
    await wrapper.setProps({ admin: true })
    await flushPromises()
    expect(getCards).toHaveBeenLastCalledWith(filter, { page: 1, page_size: 12, as_of: undefined }, true, expect.any(AbortSignal))
    wrapper.unmount()
  })
  it('keeps cards during refresh but clears them immediately when scope changes', async () => {
    const wrapper = create()
    await flushPromises()
    vi.mocked(getCards).mockImplementation(() => new Promise(() => {}))
    await wrapper.setProps({ refreshKey: 1 })
    expect(wrapper.findAll('article')).toHaveLength(1)
    expect(wrapper.find('[role="status"]').text()).toBe('Updating')
    expect(wrapper.find('[aria-label="Next page"]').attributes('disabled')).toBeDefined()
    await wrapper.setProps({ filter: { ...filter, groupIds: [9] } })
    expect(wrapper.findAll('article')).toHaveLength(0)
    wrapper.unmount()
  })
  it('removes retained cards after a failed refresh and supports retry', async () => {
    const wrapper = create()
    await flushPromises()
    vi.mocked(getCards).mockRejectedValueOnce(new Error('unavailable'))
    await wrapper.setProps({ refreshKey: 1 })
    await flushPromises()
    expect(wrapper.findAll('article')).toHaveLength(0)
    expect(wrapper.find('[role="alert"]').exists()).toBe(true)
    await wrapper.find('[aria-label="Refresh"]').trigger('click')
    await flushPromises()
    expect(wrapper.findAll('article')).toHaveLength(1)
    expect(wrapper.find('[role="alert"]').exists()).toBe(false)
    wrapper.unmount()
  })
  it('shows independent evidence without hiding low-sample values', async () => {
    const fixture = response()
    Object.assign(fixture.items[0]!.windows.h24, { observation_evidence: { tps: 'low_sample', visible_ttft: 'valid', cache: 'no_data' } })
    vi.mocked(getCards).mockResolvedValue(fixture as never)
    const wrapper = create()
    await flushPromises()
    const evidence = wrapper.findAll('.sample-state').map(node => node.text())
    expect(evidence).toEqual(['Low sample', 'Sample threshold met', 'No measurable samples'])
    expect(wrapper.text()).toContain('~ 41.58 tok/s')
    wrapper.unmount()
  })
  it('never treats old payloads as sufficient evidence', async () => {
    const wrapper = create()
    await flushPromises()
    expect(wrapper.text()).toContain('Evidence unavailable')
    expect(wrapper.text()).not.toContain('Sample threshold met')
    wrapper.unmount()
  })
  it('aborts an in-flight request on unmount', () => {
    vi.mocked(getCards).mockImplementationOnce(() => new Promise(() => {}))
    const wrapper = create()
    const signal = vi.mocked(getCards).mock.calls[0]![3]!
    expect(signal.aborted).toBe(false)
    wrapper.unmount()
    expect(signal.aborted).toBe(true)
  })
  it('handles an unavailable endpoint without displaying old values', async () => {
    vi.mocked(getCards).mockRejectedValue(new Error('404'))
    const wrapper = create()
    await flushPromises()
    expect(wrapper.find('[role="alert"]').exists()).toBe(true)
    expect(wrapper.findAll('article')).toHaveLength(0)
    wrapper.unmount()
  })
  it('ignores late responses after filter changes', async () => {
    let resolve!: (value: never) => void
    vi.mocked(getCards).mockImplementationOnce(() => new Promise(done => { resolve = done }))
    const wrapper = create()
    await wrapper.setProps({ filter: { ...filter, models: ['new'] } })
    await flushPromises()
    resolve({ ...response(), items: [] } as never)
    await flushPromises()
    expect(wrapper.findAll('article')).toHaveLength(1)
    wrapper.unmount()
  })
})
