package service

import (
	"context"
	"fmt"
	"net/http"
	"strings"

	infraerrors "github.com/Wei-Shaw/sub2api/internal/pkg/errors"
	"github.com/gin-gonic/gin"
	"github.com/tidwall/sjson"
)

const (
	codexIdentityFinalizerV2ExtraKey = "codex_identity_finalizer_v2"
	codexProtocolProfileName         = "codex-current"
	codexBodyPolicyVersion           = "responses-v1"
	codexHTTPBetaValue               = "responses=experimental"
)

// CodexProtocolProfile freezes the protocol declarations that must move as one
// unit. Existing endpoint-specific compatibility rules may choose not to emit a
// beta value, but they must never synthesize a different UA/version/originator
// tuple after this profile has been snapshotted.
type CodexProtocolProfile struct {
	Name              string
	UserAgent         string
	Originator        string
	Version           string
	HTTPBeta          string
	WSBetaV1          string
	WSBetaV2          string
	BodyPolicyVersion string
}

func completeCodexProtocolProfile(profile CodexProtocolProfile) CodexProtocolProfile {
	profile.Name = codexProtocolProfileName
	profile.HTTPBeta = codexHTTPBetaValue
	profile.WSBetaV1 = openAIWSBetaV1Value
	profile.WSBetaV2 = openAIWSBetaV2Value
	profile.BodyPolicyVersion = codexBodyPolicyVersion
	return profile
}

// CodexIdentitySnapshot is generated once for one upstream attempt/turn and is
// then shared by HTTP headers, JSON client_metadata, WS dial headers and the WS
// response.create payload. In particular, turnID and turnStartedAtUnixMs must
// never be regenerated by an individual sink.
type CodexIdentitySnapshot struct {
	mode                        codexFingerprintMode
	installationID              string
	sessionID                   string
	threadID                    string
	turnID                      string
	windowID                    string
	turnStartedAtUnixMs         int64
	clientRequestID             string
	protocolProfile             string
	learnedOfficialInstallation bool
}

// Keep the old internal name as a source-compatible alias while callers move
// to the explicit finalizer vocabulary.
type codexFingerprintIDs = CodexIdentitySnapshot

func codexIdentityFinalizerV2Enabled(account *Account) bool {
	if account == nil || account.Extra == nil {
		return false
	}
	enabled, _ := account.Extra[codexIdentityFinalizerV2ExtraKey].(bool)
	return enabled
}

// resolveCodexFingerprintModeForFinalizer uses off for an unset mode, making
// convergence explicit opt-in. A malformed value can never silently enter session,
// window40 or full. Legacy accounts fail safe to off; accounts that explicitly
// enable finalizer v2 receive a structured request error.
func resolveCodexFingerprintModeForFinalizer(account *Account) (codexFingerprintMode, error) {
	if account == nil || !account.IsOpenAIOAuth() {
		return codexFingerprintOff, nil
	}
	raw := strings.TrimSpace(account.GetExtraString(codexFingerprintModeExtraKey))
	if raw == "" {
		// Default to account-stable device identity; explicit "off" remains an opt-out.
		return codexFingerprintDevice, nil
	}
	mode := codexFingerprintMode(raw)
	switch mode {
	case codexFingerprintOff, codexFingerprintDevice, codexFingerprintSession, codexFingerprintWindow, codexFingerprintWindow40, codexFingerprintFull:
		return mode, nil
	default:
		if codexIdentityFinalizerV2Enabled(account) {
			return codexFingerprintOff, infraerrors.Newf(
				http.StatusBadRequest,
				"OPENAI_CODEX_IDENTITY_MODE_INVALID",
				"invalid %s %q",
				codexFingerprintModeExtraKey,
				raw,
			)
		}
		return codexFingerprintOff, nil
	}
}

// finalizeCodexOAuthIdentity resolves raw client signals exactly once for an
// attempt/turn. It is intentionally side-effect free; sinks only apply the
// returned immutable snapshot.
func finalizeCodexOAuthIdentity(account *Account, c *gin.Context, clientHeaders http.Header, promptCacheKey string) (*CodexIdentitySnapshot, error) {
	mode, err := resolveCodexFingerprintModeForFinalizer(account)
	if err != nil {
		return nil, err
	}
	if mode == codexFingerprintOff {
		return nil, nil
	}
	clientSeed := extractClientThreadSeed(clientHeaders, promptCacheKey)
	if clientSeed == "" && c != nil {
		clientSeed = explicitOpenAIHeaderSessionID(c)
	}
	if mode == codexFingerprintWindow40 {
		clientSeed = combineCodexFingerprintSeed(codexFingerprintTenantSeed(c), clientSeed)
	}
	snapshot := resolveCodexFingerprintIDs(account, clientSeed, mode)
	if snapshot != nil {
		snapshot.clientRequestID = snapshot.turnID
		snapshot.protocolProfile = codexProtocolProfileName
		adoptOfficialCodexInstallationID(account, clientHeaders, snapshot)
	}
	return snapshot, nil
}

func (s *OpenAIGatewayService) resolveCodexOutboundPromptCacheKey(c *gin.Context, account *Account, snapshot *CodexIdentitySnapshot, rawSessionID string) string {
	if snapshot != nil && snapshot.mode != codexFingerprintDevice && strings.TrimSpace(snapshot.sessionID) != "" {
		return strings.TrimSpace(snapshot.sessionID)
	}
	rawSessionID = strings.TrimSpace(rawSessionID)
	if rawSessionID == "" {
		return ""
	}
	return s.openAIOutboundSessionID(account, getAPIKeyIDFromContext(c), rawSessionID)
}

// finalizeCodexOAuthBody is the sole OAuth body identity boundary. Fingerprint
// and account-scoped modes are mutually exclusive, but both are kept here so
// request builders cannot accidentally change their relative order.
func (s *OpenAIGatewayService) finalizeCodexOAuthBody(
	ctx context.Context,
	c *gin.Context,
	account *Account,
	body []byte,
	snapshot *CodexIdentitySnapshot,
	accountIdentitySessionID string,
) ([]byte, error) {
	updated, err := applyCodexFingerprintToRawBody(body, snapshot)
	if err != nil {
		return nil, err
	}
	if !isOpenAIResponsesCompactPath(c) {
		cacheKey := s.resolveCodexOutboundPromptCacheKey(c, account, snapshot, accountIdentitySessionID)
		if cacheKey != "" {
			updated, err = sjson.SetBytes(updated, "prompt_cache_key", cacheKey)
			if err != nil {
				return nil, fmt.Errorf("set Codex prompt cache key: %w", err)
			}
		}
	}
	return s.applyOpenAIAccountScopedBody(ctx, c, account, updated, accountIdentitySessionID)
}

// finalizeCodexOAuthHeaders runs after inbound passthrough and account header
// overrides. No managed identity writer may run after this function.
func (s *OpenAIGatewayService) finalizeCodexOAuthHeaders(
	ctx context.Context,
	c *gin.Context,
	account *Account,
	headers http.Header,
	snapshot *CodexIdentitySnapshot,
	accountIdentitySessionID string,
) {
	sanitizeCodexOAuthHeaders(headers)
	s.applyOpenAIOutboundIdentityPolicy(ctx, account, headers, openAIOutboundOAuthPolicy)
	s.applyOpenAIAccountScopedHeaders(ctx, c, account, headers, accountIdentitySessionID)
	applyCodexFingerprintHeaders(headers, snapshot)
	outboundSessionID := resolveCodexSessionHeader(headers)
	if outboundSessionID == "" && strings.TrimSpace(accountIdentitySessionID) != "" {
		outboundSessionID = s.resolveCodexOutboundPromptCacheKey(c, account, snapshot, accountIdentitySessionID)
	}
	normalizeCodexOAuthHeaders(headers, outboundSessionID, resolveCodexThreadHeader(headers))
	// Messages compatibility intentionally has no synthetic conversation when
	// the client did not provide one. Keep this policy inside the final boundary
	// so no bridge needs a post-finalizer identity deletion.
	if isOpenAICompatMessagesBridgeContext(c) && c != nil && strings.TrimSpace(c.GetHeader("conversation_id")) == "" {
		deleteOpenAIHeaderEqualFold(headers, "conversation_id")
	}
	applyCodexOAuthStableEnvironmentHeaders(headers, account)
	applyOpenAICodexBetaFeatures(c, account, headers)
}
